import telebot
from services import ImageService

def register_handlers(bot: telebot.TeleBot, image_service: ImageService) -> None:
    """Register image generation command handler"""
    
    @bot.message_handler(commands=['image'])
    def handle_image_command(message):
        """Generate AI image from text prompt"""
        prompt = message.text.replace('/image', '').strip()
        
        if not prompt:
            bot.reply_to(
                message,
                "🎨 Please provide a description!\n\n"
                "Example: `/image a sunset over mountains`",
                parse_mode="Markdown"
            )
            return
        
        # Send loading message
        loading_msg = bot.reply_to(message, "🎨 *Creating your masterpiece...* 🖌️", parse_mode="Markdown")
        
        try:
            image_url = image_service.generate_image_url(prompt)
            
            # Delete loading message
            bot.delete_message(message.chat.id, loading_msg.message_id)
            
            # Send the generated image
            bot.send_photo(
                message.chat.id,
                image_url,
                caption=f"🖼️ *Prompt:* {prompt}\n\n✨ Generated by AI",
                parse_mode="Markdown",
                reply_to_message_id=message.message_id
            )
            
        except Exception as e:
            print(f"Image generation error: {e}")
            bot.edit_message_text(
                f"❌ Failed to generate image: {str(e)}",
                chat_id=message.chat.id,
                message_id=loading_msg.message_id
            )
